# Generated by Django 6.0.7 on 2026-08-01 11:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('devis', '0002_devis_montant_tva_frais_devis_montant_tva_heures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('id_affaire', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_affaire', models.CharField(editable=False, max_length=30, unique=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('heures_prevues', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('heures_consommees', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('etat_avancement', models.PositiveSmallIntegerField(default=0)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('priorite', models.CharField(choices=[('Basse', 'Basse'), ('Normale', 'Normale'), ('Haute', 'Haute'), ('Critique', 'Critique')], default='Normale', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('charge_affaires', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affaires_pilotees', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affaires', to='crm.client')),
                ('devis', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='affaire', to='devis.devis')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireAffaire',
            fields=[
                ('id_commentaire', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='affaires.affaire')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentaires_affaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
