# Generated by Django 6.0.7 on 2026-08-14 09:19

import affaires.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointeAffaire',
            fields=[
                ('id_piece', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to=affaires.models.chemin_piece_jointe)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='affaires.affaire')),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_jointes_ajoutees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
    ]
