# Generated by Django 6.0.7 on 2026-07-24 16:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id_devis', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(editable=False, max_length=30)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('est_courante', models.BooleanField(default=True, editable=False)),
                ('objet', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('Brouillon', 'Brouillon'), ('En_preparation', 'En préparation'), ('A_valider', 'À valider'), ('Envoye', 'Envoyé'), ('Accepte', 'Accepté'), ('Refuse', 'Refusé'), ('Annule', 'Annulé')], default='Brouillon', max_length=20)),
                ('taux_tva_defaut', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('mode_marge', models.CharField(choices=[('global', 'Global'), ('ligne', 'Ligne par ligne')], default='global', max_length=10)),
                ('type_marge', models.CharField(choices=[('pourcentage', 'Pourcentage'), ('valeur', 'Valeur')], default='pourcentage', max_length=12)),
                ('valeur_marge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mode_remise', models.CharField(choices=[('global', 'Global'), ('ligne', 'Ligne par ligne')], default='global', max_length=10)),
                ('type_remise', models.CharField(choices=[('pourcentage', 'Pourcentage'), ('valeur', 'Valeur')], default='pourcentage', max_length=12)),
                ('valeur_remise', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commentaire_justification', models.TextField(blank=True)),
                ('sous_total_heures', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_frais_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_marge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_remise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_validite', models.DateField(blank=True, null=True)),
                ('charge_affaires', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis_geres', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='crm.client')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id_historique', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ancien_statut', models.CharField(blank=True, max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='devis.devis')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneFrais',
            fields=[
                ('id_ligne', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('type_frais', models.CharField(choices=[('deplacement', 'Déplacement'), ('achat', 'Achat'), ('sous_traitance', 'Sous-traitance'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marge_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remise_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_frais', to='devis.devis')),
            ],
        ),
        migrations.CreateModel(
            name='LigneHeure',
            fields=[
                ('id_ligne', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profil', models.CharField(blank=True, max_length=100)),
                ('heures_prevues', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cout_horaire_reference', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cout_horaire_applique', models.DecimalField(decimal_places=2, max_digits=8)),
                ('marge_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remise_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_heures', to='devis.devis')),
                ('intervenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_devis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='devis',
            constraint=models.UniqueConstraint(fields=('numero', 'version'), name='unique_numero_version'),
        ),
    ]
