# Generated by Django 6.0.7 on 2026-07-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='montant_tva_frais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='devis',
            name='montant_tva_heures',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
