# Generated by Django 6.0.7 on 2026-08-13 09:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_devis_montant_tva_frais_devis_montant_tva_heures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligneheure',
            name='devis',
        ),
        migrations.RemoveField(
            model_name='ligneheure',
            name='intervenant',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='mode_marge',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='mode_remise',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='montant_tva_frais',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='montant_tva_heures',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='sous_total_heures',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='total_frais_ht',
        ),
        migrations.AddField(
            model_name='devis',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='devis',
            name='taux_tva_defaut',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id_ligne', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.devis')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.DeleteModel(
            name='LigneFrais',
        ),
        migrations.DeleteModel(
            name='LigneHeure',
        ),
    ]
