# Generated by Django 6.0.7 on 2026-08-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_remove_ligneheure_devis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
