# Generated by Django 6.0.7 on 2026-08-28 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0004_alter_lignedevis_montant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireDevis',
            fields=[
                ('id_commentaire', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentaires_devis', to=settings.AUTH_USER_MODEL)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='devis.devis')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
