# Generated by Django 6.0.7 on 2026-08-14 09:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affaires', '0002_piecejointeaffaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_facture', models.CharField(editable=False, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('Brouillon', 'Brouillon'), ('Envoyee', 'Envoyée'), ('Payee', 'Payée'), ('Partiellement_payee', 'Partiellement payée'), ('En_retard', 'En retard'), ('Annulee', 'Annulée')], default='Brouillon', max_length=20)),
                ('date_facture', models.DateField(blank=True, null=True)),
                ('mode_reglement', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('prelevement', 'Prélèvement automatique')], default='virement', max_length=20)),
                ('conditions_paiement', models.CharField(choices=[('comptant', 'Comptant (à réception)'), ('net_15', '15 jours net'), ('net_30', '30 jours net'), ('net_45', '45 jours net'), ('net_60', '60 jours net'), ('net_90', '90 jours net'), ('fin_mois_10', '10 jours fin de mois'), ('fin_mois_30', '30 jours fin de mois'), ('fin_mois_45', '45 jours fin de mois'), ('fin_mois_60', '60 jours fin de mois')], default='net_30', max_length=20)),
                ('date_echeance', models.DateField(blank=True, editable=False, null=True)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('affaire', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='affaires.affaire')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id_ligne', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('quantite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='factures.facture')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
    ]
