# Generated by Django 6.0.7 on 2026-08-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='conditions_paiement',
        ),
        migrations.AddField(
            model_name='facture',
            name='jour_fixe_mois_suivant',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='nombre_jours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_echeance',
            field=models.CharField(choices=[('net', 'Paiement net (nombre de jours)'), ('fin_mois', 'X jours fin de mois'), ('jour_fixe', 'Jour fixe du mois suivant')], default='net', max_length=20),
        ),
    ]
