# Generated by Django 6.0.7 on 2026-08-24 13:57

import factures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_remove_facture_conditions_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=factures.models.chemin_signature),
        ),
    ]
