# Generated by Django 6.0.7 on 2026-07-24 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raison_sociale', models.CharField(max_length=255)),
                ('matricule_fiscal', models.CharField(max_length=50, unique=True)),
                ('adresse', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=100)),
                ('secteur_activite', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('Prospect', 'Prospect'), ('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Prospect', max_length=20)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
