# Generated by Django 6.0.7 on 2026-09-04 11:19

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('contract', 'Contrat'), ('technical', 'Technique'), ('financial', 'Financier'), ('legal', 'Juridique'), ('report', 'Rapport'), ('other', 'Autre')], default='other', max_length=20)),
                ('fichier', models.FileField(upload_to=documents.models.chemin_document)),
                ('lie_a', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_ajoutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
